before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
env:
  global:
    secure: "d56saag9KkBEdmM4C+ZxRWZHAZIgq8QehFWlGSxsjvyE5YP70zFTGmyqXFLH4pfaHxhlKYP/0GOLPoRUFjaDnuyQWG0VOnLYFWwHQoX0FL6z2KgAOvaGDUv21OlQt7JW+0W31Qf4KytzOckuIuoRw0hpfTJ5wNdk8eCWnJHTNaw="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
